# Generated by Django 5.2.5 on 2025-08-18 22:45:00

from django.db import migrations

def create_st_edward_parish(apps, schema_editor):
    """Create the default St. Edward Church parish if it doesn't exist"""
    Parish = apps.get_model('directory', 'Parish')
    
    # Only create if it doesn't already exist
    if not Parish.objects.filter(slug='st-edward').exists():
        Parish.objects.create(
            name='St. Edward Church',
            slug='st-edward'
        )

def reverse_st_edward_parish(apps, schema_editor):
    """Remove the St. Edward Church parish"""
    Parish = apps.get_model('directory', 'Parish')
    Parish.objects.filter(slug='st-edward').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_st_edward_parish, reverse_st_edward_parish),
    ]
